WIP: Feat integration with sanity
renanpontez/agility-app pull request #21
Opened 2024-12-09 17:05 UTC by femacedogomes

Integração inicial do sanity com a página de currículo pessoal da agility

2024-12-14 15:16 UTC, renanpontez commented on next.config.mjs
> +      },
Isso foi recomendacao de alguma doc? Pode mandar pra eu ver o que e direitinho?

Vi outros next.config de projetos com Sanity aqui e nao tem essas linhas, na verdade tem outras que nao sei se sao necessarias.

2024-12-14 15:16 UTC, renanpontez commented on sanityClient.ts
> +  projectId: '0bz33x6i',
Pelo amor de Jesa colocar isso em .ENV meu pleno (vulnerabilidade grande aqui)

2024-12-14 15:17 UTC, renanpontez commented on sanityClient.ts
> +  dataset: 'production',
jogar pra .ENV tbm

2024-12-14 15:17 UTC, renanpontez commented on sanityClient.ts
> +  tel,
tel? really? aloooooooowww kkkkkkkkkkk

2024-12-14 15:18 UTC, renanpontez commented on sanityClient.ts
> +  cvLink,
`resumeDownloadURL`

2024-12-14 15:18 UTC, renanpontez commented on sanityClient.ts
> +  "image": image.asset->url,
E se a gente tiver mais imagens na pagina? Como diferenciar o que é "image"?

2024-12-14 15:19 UTC, renanpontez commented on sanityClient.ts
> +  jobs,
`headline`

2024-12-14 15:19 UTC, renanpontez commented on sanityClient.ts
> +  workDescription,
`description` - nao precisa ter 2, inclusive gera mais complicacao ter 2 - o bloco do Sanity ja resolve o problema (inclusive ele e a feature principal do Sanity eu diria hahah)

2024-12-14 15:22 UTC, renanpontez commented on src/components/Atoms/IconPickerClient/IconPickerClient.tsx
Tipo tudo bem criar uma pasta nova do nada e colocar um atomo la - se tiver combinado que vai mudar o padrao de pastas (ai tu teria que colocar todos os atomos ai dentro)

Colocar so o IconPickerClient e deixar o resto fora parece gambs - pq nao colocar fora igual ao Button por exemplo?

Se tu achar interessante organizar as pastas no modelo atom/mol/org bora trocar ideia e criar um PR so pra isso, bota fe?

Padroessssss

2024-12-14 15:36 UTC, renanpontez commented on src/components/Atoms/IconPickerClient/IconPickerClient.tsx
E nao precisava nem ter criado esse HOC, nao entendi pq ele existe. Tu deveria buscar do Sanity so o icone mesmo. 


https://www.sanity.io/plugins/icon-picker > pesquisa como fazer no Store SVG

O mais ideal no front é tu recebero svg e injetar no codigo via `dangerouslySetInnerHTML` passando icon.svg (tem uns exemplos ai na net quando fiz a primeira vez fui procurando no google)

2024-12-14 15:37 UTC, renanpontez commented on src/components/Atoms/IconPickerClient/IconPickerClient.tsx
Se precisar ter um hoc so pra icone bora chamar so de `iconPicker`

2024-12-14 15:37 UTC, renanpontez commented on src/types/sanity.ts
> +export type IiconPicker = {
padroess

2024-12-14 15:39 UTC, renanpontez commented on src/types/sanity.ts
> +};
Pergunta reflexiva (nao precisa responder): pq em outros arquivos tu nao tipou com o padrao `INameOfData` que tem nesse arquivo?

Outra, qual a diferenca de `type` e `interface`?

2024-12-14 15:40 UTC, renanpontez commented on src/utils/redirectToWpp.ts
redirectToWhatsApp

2024-12-14 15:41 UTC, renanpontez requested changes
Reviewed

2024-12-14 15:55 UTC, renanpontez commented on sanityClient.ts
Pensando quando a gente tiver uns 50 schemas (projeto, proposta, curriculo, team member, etc) - sera que 1 arquivo sanityClient para todas as request vai ser good de manter? 

Acho que seria melhor pelo menos separar os arquivos de fetch em categorias

2024-12-14 20:04 UTC, femacedogomes commented on sanityClient.ts
> +  "image": image.asset->url,
corrigido pra userImage

2024-12-14 20:06 UTC, femacedogomes commented on sanityClient.ts
> +  workDescription,
Já tinha corrigido isso dentro do componente mas faltava na Querry. Perdão.

2024-12-16 15:20 UTC, femacedogomes commented on src/types/sanity.ts
> +};
Confeso que não sabia ao pé da letra as diferenças entre type e interface e tive que pesquisar. Eu sabia que as duas são utilizadas para criar tipagens, mas existiam implementações que há distinguiam. Nós utilizamos a interface no projeto anterior, mas quando fui utilizar neste, o eslint me corrigiu para utilizar o type. Ainda não utilizei o recurso que os distinguem, como as funcionalidades do type aliases.

2024-12-16 15:24 UTC, femacedogomes commented on src/types/sanity.ts
> +};
Por não se tratar mais de interfaces, foi remover o "I" inicial.

2024-12-16 16:01 UTC, femacedogomes commented on sanityClient.ts
Criado a pasta services/sanity/TeamMemberServices

2025-01-08 15:21 UTC, merged