WIP: simple breadcrumb component
renanpontez/agility-app pull request #22
Opened 2024-12-11 18:54 UTC by femacedogomes

Um bread crumb simples, sem props de estilos.

2024-12-14 15:00 UTC, renanpontez commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +    { name: params.slug, href: '',
se nao tem `href` nao manda, acaba se tornar isso e "dado sujo"

2024-12-14 15:03 UTC, renanpontez commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +  const BreadCrumpItems: BreadCrumbItemsProps[] = [
O nome é breadcrumb. Uma regra pra case é colocar quando começa palavras diferentes. (compartilhando +1 vez a guideline da Google pra um monte de coisas: https://google.github.io/styleguide/jsguide.html)


O ideal seria: `breadcrumbItems` ou `BreadcrumbItems` - apesar de eu nao ver pq colocar com maiusculo.

Ai man, sempre que tiver duvida em Javascript usa `[lowerCamelCase](https://pt.wikipedia.org/wiki/CamelCase#:~:text=CamelCase%20%C3%A9%20a%20denomina%C3%A7%C3%A3o%20em,defini%C3%A7%C3%B5es%20de%20classes%20e%20objetos.)` (

2024-12-14 15:05 UTC, renanpontez commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +  const BreadCrumpItems: BreadCrumbItemsProps[] = [
Resolvi escrever um pouquinho a mais nessa "besteira"  justamente por ser uma besteira. O pleno evita ao maximo errar namings e organizacao de arquivos. O padrao é muito importante na programação - tenta dar atencao aos nomes em ingles e ao formato de escrita (`lowerCamelCase` de preferencia em js)

2024-12-14 15:07 UTC, renanpontez commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +  const BreadCrumpItems: BreadCrumbItemsProps[] = [
BreadCrumb (ou breadCrumb) estaria certo se a gente tivesse falando de 2 palavras mas e so 1 kkkk

2024-12-14 15:09 UTC, renanpontez commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +      </div>
Sera que quando eu for usar o Breadcrumb em outras paginas, vou ter que levar o wrapper (`<div className="container pt-4">`)?

Pq se sim, isso precisa ta dentro do Breadcrumb ne? Senao vou ter o mesmo retrabalho em todas as instancias.

Agora se esse container ai for especificamente pra tela de portfolio e nos outros locais que a gente for usar, ele ir raw apenas `<Breadcrumb />` ai tudo bem pq é especificidade da pagina

2024-12-14 15:10 UTC, renanpontez commented on src/components/Atoms/BreadCrumb/BreadCrumb.tsx
> +  href: string;
href é opcional

2024-12-14 15:11 UTC, renanpontez requested changes
Reviewed

2024-12-14 15:13 UTC, renanpontez commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +  const BreadCrumpItems: BreadCrumbItemsProps[] = [
https://www.youtube.com/watch?v=RFFsT5YQuSQ

2024-12-14 19:06 UTC, femacedogomes commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +  const BreadCrumpItems: BreadCrumbItemsProps[] = [
Eu achei que fossem 2 palavras e coloquei sempre o "C" de crumb em maísculo (o que não deixa de ser falha minha).
Agora na hora de criar a const do breadcrumbItems realmente foi uma baita falta de atenção mesmo. Escrevi errado trocando o 'b' pelo 'p' e ainda coloquei em maiúsculo mesmo conhecendo as praticas do camelCase. Agradeço demais por dar bastante atenção nisso. Eu consideraria uma falha que até junior não deveriam cometer.

2024-12-14 19:10 UTC, femacedogomes commented on src/app/[locale]/portfolio/[slug]/page.tsx
> +      </div>
Sim. Seria uma boa prática pra evitar a repetição dele nesse prójeto.
Eu deixei o mais atômico possível pensando um pouco no agility-wind também, mas incrementas essas propriedades de classe dentro do atomo.

2024-12-23 21:56 UTC, renanpontez approved these changes

2024-12-26 19:19 UTC, merged